#!/usr/bin/env bash

declare -a STOW_FOLDERS=(
  "aliases"
  "bin"
  "nvim"
  "tmux"
  "zsh"
)

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/dotfiles
fi

pushd $DOTFILES &> /dev/null

for folder in ${STOW_FOLDERS[@]}; do
  stow --restow $folder
done

popd &> /dev/null
