call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-git'
Plug 'sbdchd/neoformat'

" LANGUAGE RELATED
" ----------------

" Language pack that includes most languages
Plug 'sheerun/vim-polyglot'

" Javascript
Plug 'moll/vim-node', { 'for': ['javascript', 'js', 'jsx'] }
Plug 'othree/javascript-libraries-syntax.vim', { 'for': ['javascript', 'js', 'jsx'] }
Plug 'neoclide/vim-jsx-improve', { 'for': ['javascript', 'js', 'jsx'] }
Plug '1995eaton/vim-better-javascript-completion', { 'for': [ 'javascript', 'js', 'jsx' ]}
Plug 'ternjs/tern_for_vim', { 'do': 'npm install' }

" GraphQL
Plug 'jparise/vim-graphql'

" Typescript
Plug 'leafgarland/typescript-vim', { 'for': ['typescript'] }
Plug 'HerringtonDarkholme/yats.vim', { 'for': ['typescript'] }
Plug 'Quramy/tsuquyomi', { 'for': ['typescript'] }

" Text
Plug 'ntpeters/vim-better-whitespace'
Plug 'PeterRincker/vim-argumentative'
Plug 'Raimondi/delimitMate'
Plug 'tpope/vim-repeat'
Plug 'vim-scripts/ruby-matchit', { 'for': 'ruby' }
Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-datetime'
Plug 'kana/vim-textobj-function'
Plug 'lucapette/vim-textobj-underscore'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'thinca/vim-textobj-function-javascript', { 'for': [ 'javascript', 'js', 'jsx' ]}

" Framework
Plug 'avdgaag/vim-phoenix'
Plug 'tpope/vim-rails'

" Happiness
Plug 'tpope/vim-db'
Plug 'rking/ag.vim'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'FelikZ/ctrlp-py-matcher'
" Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
" Plug 'airblade/vim-gitgutter'
Plug 'Olical/vim-enmasse', { 'on': 'EnMasse' }
" Plug 'suan/vim-instant-markdown', { 'for': 'markdown', 'do': 'npm -g install instant-markdown-d' }
Plug 'scrooloose/nerdtree', { 'on': ['NERDTreeToggle', 'NERDTreeFind'] }
Plug 'thoughtbot/vim-rspec', { 'for': 'ruby', 'on': ['RunCurrentSpecFile', 'RunNearestSpec', 'RunLastSpec', 'RunAllSpecs'] }
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
" Plug 'marijnh/tern_for_vim', { 'do': 'npm install' }
Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-unimpaired'
Plug 'SirVer/ultisnips'
" Plug 'rizzatti/dash.vim', { 'on': ['Dash', 'DashKeywords'] }
Plug 'mattn/emmet-vim'
Plug 'ervandew/supertab'
" Plug 'Valloric/YouCompleteMe', { 'do': './install.py --js-completer' }
Plug 'w0rp/ale'
Plug 'wakatime/vim-wakatime'

" Colors
Plug 'kristijanhusak/vim-hybrid-material'
call plug#end()

let mapleader=','

function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
      execute 'source' config_file
    endif
  endfor
endfunction

" Set plugin specific settings
call s:SourceConfigFilesIn('plugins')

syntax enable
set t_Co=256
set background=dark
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1
colorscheme hybrid_material

set backspace=indent,eol,start
set autoindent
set history=500
set showcmd
set tabstop=2 softtabstop=2 shiftwidth=2
set expandtab
set smarttab
set visualbell
set splitright
set splitbelow
set timeoutlen=400
set cursorline
set shiftround
set colorcolumn=80
set wildmenu
set wildmode=list:longest
set encoding=utf-8 fileencoding=utf-8 termencoding=utf-8
set scrolloff=4
set sidescrolloff=5
set nowrap
set nobackup
set t_ut=
set hidden
set noswapfile
set autoread
set lazyredraw
set suffixesadd+=.jsx.coffee,.coffee,.js.coffee
set clipboard+=unnamed
set incsearch
set hlsearch
nohlsearch " Kill Highlighting on vimrc reload
set ruler
set laststatus=2 " Always show status line
set completeopt-=preview

set wildignore+=*/tmp*/,*.swp,*.zip,*.scssc
set wildignore+=*/generated/*,*/images/*,*/node_modules/*,tmp/*

set relativenumber
if v:version >= 704
  set number
endif

runtime macros/matchit.vim " use % to jump between start/end of methods

command! Q q
command! W w
command! Wq wq
command! Qa qa

" Use 0 to go to first character instead of beginning of line
nnoremap 0 ^

nnoremap <C-h> <C-W><C-h>
nnoremap <C-j> <C-W><C-j>
nnoremap <C-k> <C-W><C-k>
nnoremap <C-l> <C-W><C-l>

inoremap jk <esc>
inoremap Jk <esc>

nnoremap <leader>pi :PlugInstall<cr>
nnoremap <leader>vi :sp $MYVIMRC<cr>
nnoremap <leader>so :source $MYVIMRC<cr>

nnoremap <leader>p viwp<ESC>b
nnoremap <leader>ch :silent noh<cr>

" convert erb to haml using html2haml gem
nmap <leader>h2h :%!html2haml --erb 2> /dev/null<CR>:set ft=haml<CR>
vmap <leader>h2h :!html2haml --erb 2> /dev/null<CR>

" replace word under cursor
nnoremap <leader>s :%s/\<<C-r><C-w>\>/

let g:neoformat_try_formatprg = 1

augroup filetypes
  autocmd!

  autocmd BufNewFile,BufReadPost .eslintrc,.babelrc set filetype=json
  autocmd BufNewFile,BufReadPost *.hamlc set filetype=haml
  autocmd BufRead,BufNewFile *.md setlocal textwidth=80
  autocmd filetype help call HelpFileMode()

  autocmd FileType ruby,eruby,yaml setlocal path+=lib
  autocmd FileType ruby,eruby,yaml setlocal iskeyword+=?
augroup END

function! HelpFileMode()
  nnoremap <buffer> <cr> <c-]>
  nnoremap <buffer> <bs> <c-T>
  nnoremap <buffer> q :q<cr>
endfunction

let @b="dir]pkk2dd"
nnoremap <leader>pir @b

let @i='/if\\d$O"j>>oend:noh\\k0'
nnoremap <leader>if @i

" Override colorscheme to show backgrounds on search terms instead of
" underlines
highlight Search ctermfg=black ctermbg=yellow cterm=NONE guifg=black guibg=yellow gui=NONE

highlight clear SignColumn

" Allow for settings specific to machines this runs on
if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

let $BASH_ENV = '~/.bash_aliases'
