#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Disable analytics
brew analytics off

# Add font cask to install nerd fonts
brew tap homebrew/cask-fonts
