#!/usr/bin/env bash

brew_install() {
  local formula="$1"
  local options="$2"

  if ! brew list $formula &> /dev/null; then
    brew install $formula $options
  fi
}

brew_install gh
brew_install git
brew_install fnm
brew_install jq
brew_install neovim
brew_install tmux
brew_install fzf
brew_install stow

# Needed for telescope.nvim
brew_install fd
brew_install ripgrep
