# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts
# font_family      Monaspace Neon
font_family      JetBrains Mono NL
# bold_font        Monaspace Neon SemiBold
# italic_font      Monaspace Neon Italic
# bold_italic_font Monaspace Neon SemiBold Italic

# font_features    MonaspaceNeon-Regular        +ss06 +ss07 +ss08 +ss09 +calt +liga
# font_features    MonaspaceNeon-SemiBold       +ss06 +ss07 +ss08 +ss09 +calt +liga
# font_features    MonaspaceNeon-Italic         +ss06 +ss07 +ss08 +ss09 +calt +liga
# font_features    MonaspaceNeon-SemiBoldItalic +ss06 +ss07 +ss08 +ss09 +calt +liga

font_size 13.0
modify_font cell_height 125%
undercurl_style thick-sparse

window_padding_width 4

#: Cursor customization
cursor_shape block
cursor_blink_interval 0

#: Terminal bell
enable_audio_bell no

#: Tab bar
tab_bar_edge top
tab_bar_style powerline

#: Scrollback
scrollback_lines 10000

#: Advanced
shell_integration no-cursor

map cmd+c copy_to_clipboard

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
